
server:
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
#    password: websike123
#    url: jdbc:mysql://database-2.cpq4qsyguy1e.ap-southeast-1.rds.amazonaws.com:3306/barkstore_inv
#    username: websike123
    password: root
    url: jdbc:mysql://localhost:3306/barkstore_inv
    username: root
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      max-lifetime: 1800000      # 30 min
#      idle-timeout: 300000       # 10 min
#      connection-timeout: 20000  # 20 sec
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          envers:
            revision_table_name: customrevinfo
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
        show-sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
  mail:
    host: smtp.gmail.com
    port: 587
    username: websikexyz@gmail.com
    password: taqq uipf shqp pvgn

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000



