#spring.datasource.url=jdbc:mysql://localhost:3306/barkstore
#spring.datasource.lastName=root
#spring.datasource.password=root
#
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl.auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
#    password: barkstorewebsike
#    url: jdbc:mysql://barkstoresystem.cpq4qsyguy1e.ap-southeast-1.rds.amazonaws.com:3306/barkstore_inv
#    username: websike
    password: root
    url: jdbc:mysql://localhost:3306/barkstore_inv
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
        show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gusteng211@gmail.com
    password: ycnp kdha ftku bcny

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000